/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.JogadoresController;
import Model.*;
import javax.swing.JOptionPane;

/**
 *
 * @author André Hugo
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    private static TelaInicial ourInstance = new TelaInicial();

    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJogar = new javax.swing.JButton();
        btnScoreboad = new javax.swing.JButton();
        btnSobre = new javax.swing.JButton();
        lblImagemPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 650));
        setMinimumSize(new java.awt.Dimension(800, 650));
        setResizable(false);

        btnJogar.setText("Jogar");
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });

        btnScoreboad.setText("ScoreBoard");
        btnScoreboad.setEnabled(false);
        btnScoreboad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScoreboadActionPerformed(evt);
            }
        });

        btnSobre.setText("Sobre");
        btnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreActionPerformed(evt);
            }
        });

        lblImagemPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblImagemPrincipal.setText("Pegada Ecológica em Java");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnScoreboad, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagemPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblImagemPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(btnJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnScoreboad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnScoreboadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScoreboadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnScoreboadActionPerformed

    private void btnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Esse trabalho é baseado no quiz Pegada Ecológica do INPE,\ndesenvolvido em Java para a Atividade Prática Supervisionada.");
    }//GEN-LAST:event_btnSobreActionPerformed

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        // TODO add your handling code here: 
        boolean permitido = true;
        try {
            int confirmacao = 1;
            while(confirmacao == 1){
                int confirmacaoNome = 0;
                String nomeJogador = "";
                String idadeJogador = "";
                while(nomeJogador.isEmpty() || idadeJogador.isEmpty()){
                    nomeJogador = JOptionPane.showInputDialog("Qual seu nome, jogador(a)?\n");
                    idadeJogador = JOptionPane.showInputDialog("Qual sua idade?");
                    if(nomeJogador.isEmpty() || idadeJogador.isEmpty()){
                        JOptionPane.showMessageDialog(null,"Por favor, preencha todas as informações!");
                    } else if (!idadeJogador.matches("^[0-9]*$")) {
                        JOptionPane.showMessageDialog(null, "Insira uma idade válida!");
                    }
                }
                //confirmacao = 0 é igual a "Confirmar", confirmacao = 1 é igual a "Corrigir".
                Object[] options = { "Confirmar", "Corrigir" };
                confirmacao = JOptionPane.showOptionDialog(null, "As informações fornecidas estão corretas:\n Nome: "+ nomeJogador+"\n Idade: "+idadeJogador, "Confirma?", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
                System.out.println(confirmacao);   
                Jogador jogador = new Jogador(nomeJogador, Integer.parseInt(idadeJogador));
                JogadoresController.gravaJogador(jogador);
            }
        } catch (Exception e){
            System.out.println(e);
            permitido = false;
        }
        if(!permitido){
            JOptionPane.showMessageDialog(null, "Preencha as informações corretamente para iniciar o jogo!");
        } else {
            TelaPerguntas tPerguntas = new TelaPerguntas();
            tPerguntas.setSize(800, 650);
            tPerguntas.setVisible(true);
            tPerguntas.setLocationRelativeTo(null);
            tPerguntas.setResizable(false);
            //this.setVisible(false);
        } 
    }//GEN-LAST:event_btnJogarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogar;
    private javax.swing.JButton btnScoreboad;
    private javax.swing.JButton btnSobre;
    private javax.swing.JLabel lblImagemPrincipal;
    // End of variables declaration//GEN-END:variables
}
